### ISSUE TITLE
Organigrama y primeras ideas

### ISSUE THREAD

**Issue by zikocult** [zikocult/minishell42#2]
@PatriPomes  Realizar un pequeño organigrama del proyecto y buscar las primeras ideas de como empezar.

**Comment by PatriPomes** [comment]
Tenemos issues correspondientes a las diferentes branch a modo generico ya dividido... el primer issue por el que voy a empezar es el de entender el lexico de bash ya que no se usan scipts ni argumentos... si esto lo tienes por la mano continua por el siguiente o por el que quieras... el que elijas pon un comentario indicandolo y listo
